version: '3.9'

services:
  node:
    image: ma_super_app
    container_name: node_app
    build:
      context: .
    environment:
      - DATABASE_HOST=mysql
      - DATABASE_PORT=3306
      - DATABASE_USERNAME=myuser
      - DATABASE_PASSWORD=mypassword
      - DATABASE_NAME=mydatabase
    depends_on:
      - mysql
    ports:
      - "3000:3000"
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=mydatabase
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=mypassword
    command:
      - --default-authentication-plugin=mysql_native_password # nécessaire pour éviter l'erreur ER_NOT_SUPPORTED_AUTH_MODE
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql_data:

